-module(tester).
-export([usa/0,sweden/0,bsweden/0,busa/0]).


usa() ->
	routy:start(r1, chicago),
	io:format("[Test] Started router 'chicago'~n", []),
	routy:start(r2, orlando),
	io:format("[Test] Started router 'orlando'~n", []),
	routy:start(r3, austin),
	io:format("[Test] Started router 'austin'~n", []),
	r1 ! {add, orlando, {r2, ip()}},
	io:format("[Test] Added 'orlando' to 'chicago'~n", []),
	r2 ! {add, chicago, {r1, ip()}},
	io:format("[Test] Added 'chicago' to 'orlando'~n", []),
	r2 ! {add, austin, {r3, ip()}},
	io:format("[Test] Added 'austin' to 'orlando'~n", []),
	r3 ! {add, orlando, {r2, ip()}},
	io:format("[Test] Added 'orlando' to 'austin'~n", []),
	r1 ! broadcast,
	timer:sleep(2000),
	r2 ! broadcast,
	timer:sleep(2000),
	r3 ! broadcast,
	timer:sleep(2000),
	r1 ! update,
	r2 ! update,
	r3 ! update,
	r1 ! {status, self()},
	timer:sleep(2000),
	r2 ! {status, self()},
	timer:sleep(2000),
	r3 ! {status, self()},
	timer:sleep(2000).

sweden() ->
	routy:start(r1, stockholm),
	io:format("[Test] Started router 'stockholm'~n", []),
	routy:start(r2, goteborg),
	io:format("[Test] Started router 'goteborg'~n", []),
	routy:start(r3, malmo),
	io:format("[Test] Started router 'malmo'~n", []),
	routy:start(r4, uppsala),
	io:format("[Test] Started router 'uppsala'~n", []),
	r1 ! {add, malmo, {r3, ip2()}},
	io:format("[Test] Added 'malmo' to 'stockholm'~n", []),
	r3 ! {add, stockholm, {r1, ip2()}},
	io:format("[Test] Added 'stockholm' to 'malmo'~n", []),
	r3 ! {add, goteborg, {r2, ip2()}},
	io:format("[Test] Added 'goteborg' to 'malmo'~n", []),
	r2 ! {add, malmo, {r3, ip2()}},
	io:format("[Test] Added 'malmo' to 'goteborg'~n", []),
	r4 ! {add, stockholm, {r1, ip2()}},
	io:format("[Test] Added 'stockholm' to 'uppsala'~n", []),
	r1 ! {add, uppsala, {r4, ip2()}},
	io:format("[Test] Added 'uppsala' to 'stockholm,'~n", []),
	r1 ! broadcast,
	timer:sleep(2000),
	r2 ! broadcast,
	timer:sleep(2000),
	r3 ! broadcast,
	timer:sleep(2000),
	r4 ! broadcast,
	timer:sleep(2000),
	r1 ! update,
	r2 ! update,
	r3 ! update,
	r4 ! update,
	r1 ! {status, self()},
	timer:sleep(2000),
	r2 ! {status, self()},
	timer:sleep(2000),
	r3 ! {status, self()},
	timer:sleep(2000),
	r4 ! {status, self()},
	timer:sleep(2000).

ip() -> 'usa@130.229.183.74'.
ip2() -> 'sweden@130.229.183.74'.


bsweden()->
	r1 ! broadcast,
	timer:sleep(2000),
	r2 ! broadcast,
	timer:sleep(2000),
	r3 ! broadcast,
	timer:sleep(2000),
	r4 ! broadcast,
	timer:sleep(2000),
	r1 ! update,
	r2 ! update,
	r3 ! update,
	r4 ! update,
	r1 ! {status, self()},
	timer:sleep(2000),
	r2 ! {status, self()},
	timer:sleep(2000),
	r3 ! {status, self()},
	timer:sleep(2000),
	r4 ! {status, self()},
	timer:sleep(2000).

busa()->
	r1 ! broadcast,
	timer:sleep(2000),
	r2 ! broadcast,
	timer:sleep(2000),
	r3 ! broadcast,
	timer:sleep(2000),
	r1 ! update,
	r2 ! update,
	r3 ! update,
	r1 ! {status, self()},
	timer:sleep(2000),
	r2 ! {status, self()},
	timer:sleep(2000),
	r3 ! {status, self()},
	timer:sleep(2000).

